# Generated by Django 3.1.2 on 2020-11-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePaciente', models.CharField(max_length=50, verbose_name='Nombre del Paciente')),
                ('RutPaciente', models.CharField(max_length=20, verbose_name='Rut Paciente')),
                ('NombreMedicamento', models.CharField(max_length=20, verbose_name='Nombre del Medicamento')),
                ('Dosis', models.IntegerField(verbose_name='Dosis del medicamento en gramos')),
                ('Motivo', models.TextField(verbose_name='Motivo Prescripcion')),
                ('Creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Receta')),
                ('Estado', models.BooleanField(default=True, verbose_name='Esta Activa?')),
                ('Firma', models.FileField(upload_to='', verbose_name='Archivo Firma Electronica')),
            ],
        ),
    ]
